### ISSUE TITLE
Input box is completely transparent

### ISSUE THREAD

**Issue by berarma** [daniellandau/switcher#1]
I'm running this extension in Debian Jessie, Gnome 3.14, and I don't see the input box background black, it's totally transparent and I just can barely see what I'm typing.

I like the extension, I hate the way Alt-Tab works but haven't found a good alternative until maybe now. Congratulations.

**Comment by krlmlr** [comment]
Same for me.

**Comment by lidaling** [comment]
How to fix it ?
And make input text bolder?

**Comment by daniellandau** [comment]
Sorry for taking so long to respond.

Is it Debian Jessie for all of you? I'll have to try and replicate that first. There is no explicit styling applied to the input box at the moment.

**Comment by krlmlr** [comment]
I'm on Ubuntu.

**Comment by jonnius** [comment]
I did not have that problem on Ubuntu Vivid nor on Wily.

**Comment by krlmlr** [comment]
Oh -- it's Ubuntu Gnome.

**Comment by jonnius** [comment]
Me too. Maybe it is related with another Extension or a special configuration. Could you try to create a clean test user, install only this extension and see if the problem still persists?

**Comment by berarma** [comment]
I've tried disabling all extensions and restarting gnome-shell. Still the same. I'm using the standard Adwaita theme with no customization that I know of. Could it be the other way around? Maybe the lack of styling is causing this problem on default configurations but works on some?

**Comment by daniellandau** [comment]
I could replicate with a clean VM running Ubuntu Vivid (basic server variant, not Ubuntu Gnome). I changed the extension so that there is at least some explicit styling. The end result is not exactly the same as on my machine, but at least it's visible and usable.

The new fixed version should appear at extensions.gnome.org within a couple of days once it passes review, but if you can't wait, you can just clone this repository to the correct place.

Thanks for letting me know!
