### ISSUE TITLE
Should Launcher and Switcher items be shown at the same time?

### ISSUE THREAD

**Issue by daniellandau** [daniellandau/switcher#109]
My situation for example:

I'm in the mood to do some Android development, I have a tab open in a browser with Android in the title. Then I open switcher and type android and I see my browser tab and not Android Studio.

Instead I think now that it might be better to yes show the browser window first, but maybe also show the launchable app below it too.

My two main concerns are:

1. Performance. No matter what you do (and there's lots of efforts in already to make searching all apps as fast as possible), there are always going to be more apps than windows so searching through them is slower by definition. Before adding them in the same view, async rendering as discussed in https://github.com/daniellandau/switcher/pull/81 should be added. At that point another stab could be made at enabling searching the settings items too.

2. User experience. Is it confusing to have both launchable apps and windows in the same view? I have used switcher for so long (also I wrote it) that maybe I'm biased, but I'm starting to think maybe not too much. I think it'd make sense to not show apps as "Launcher" items that already have windows open.

**Comment by jessarcher** [comment]
I would definitely be keen for this. I generally don't care if the application is open or not, I just want to get to it, whatever it takes.

Additionally, the reason I came here today was actually to see about being able to only show (or at least search) just the application name, rather than it's window title when it's already open. The scenario you mentioned about getting switched to your browser instead of your intended app because your browser title might have that word in it is very familiar to me.

Ultimately I'd like the same keystrokes to always do the same thing rather than having to assess what option is in the list. That's the reason I don't like alt+tab, because I have to make an assessment rather than just being able to summon what I'm after without thinking. It's also the reason I don't like ULauncher, because to switch to an already open window you have to prefix it with "w " which not only is extra keys, but also requires me to think about whether the app is already open.

**Comment by jessarcher** [comment]
It would probably be good to still show the window title, because in my case I sometimes have multiple terminals open. What could be really cool, but perhaps a bit too obscure, is for the first word you type to only search the application name, but if you press space the second word would filter down everything returned by the first word, but this time by window title. :woman_shrugging:

**Comment by jessarcher** [comment]
Just a quick update to say that I've realised I can fix *most* of my frustrations by experimenting with the matching algo and the ordering method.

This ~is~ was a good example of my frustration:

![image](https://user-images.githubusercontent.com/4977161/88615925-38a2e600-d0d6-11ea-8961-e4e3bf9427be.png)

But I had fuzzy combined with ordering by last focused. By changing the ordering to "most relevant" (obvious now in hindsight) I'm having a much better time. And the last focused window is still the first option when no search results are entered, so I can still use Switcher to quickly swap between the two most recent apps without having to type a search pattern.

I would definitely still love to experiment with having launcher and switcher items at the same time though as I still occasionally get the issue you mentioned where I want an app that isn't open and a window title happens to match.
