### ISSUE TITLE
Debian 10 Gnome 3.30.2 - Extension failed to load

### ISSUE THREAD

**Issue by krawetko** [daniellandau/switcher#130]
The extension fails to load on current debian, the error from the gnome-shell
`gnome-shell[8196]: Extension "switcher@landau.fi" had error: TypeError: GObject.registerClass() used with invalid base class (is NotificationPolicy)`
Anybody has an idea how to get it working?

**Comment by daniellandau** [comment]
That's strange. Which version of the extension do you have? You can check with

```
cat ~/.local/share/gnome-shell/extensions/switcher@landau.fi/metadata.json
```

The latest supported on 3.30 is version 28.

**Comment by krawetko** [comment]
i was using the latest version. But in the meantime I have migrated to debian testing which upgraded my gnome to 3.38 and with this version it is working without issues

**Comment by daniellandau** [comment]
Gnome Shell does breaking changes every now and then. You should always use the version of Switcher that declares compatibility with your version of the shell.

I might from time to time try to port the newest version of Switcher to older Gnome Shell versions, but I'm myself usually on latest Gnome so that's where the most recent version of Switcher exists too.
