### ISSUE TITLE
Weighted scoring of the search results?

### ISSUE THREAD

**Issue by mgalgs** [daniellandau/switcher#5]
Would you consider adding some sort of weighted heuristic for sorting the search results?

For example, when I launch an application from my terminal, the terminal title gets updated to contain the application name, so it shows up in my filtered results when I search for the application. I'd really like the application itself to rank higher than the terminal it was launched from.  An easy way to get that would be to rank results higher if the match was at the beginning of the candidate string.

**Comment by daniellandau** [comment]
The list is in activation order, so as long as you use the application, instead of the terminal that launched it, you should see the application first. I'm open for improvements, however. I added a point in [TODO.md](https://github.com/daniellandau/switcher/blob/master/TODO.md) for this.

**Comment by nevesnunes** [comment]
I've been working on adding a fuzzy matcher, which also uses some basic scoring instead of focus order. This scoring gives priority to prefix matches, specially application name. Maybe it would be interesting to have scoring as an option, in order to be also used in the normal substring matcher.

@daniellandau, if this sounds good, let me know so I can work on a pull request.

**Comment by daniellandau** [comment]
Sure. I've been happy with the focus order, so I wouldn't make any other order the default, but adding options (that are clearly documented to the user) is fine by me.

**Comment by daniellandau** [comment]
This is fixed by https://github.com/daniellandau/switcher/pull/19, thanks @nevesnunes.
